# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.admin.organisation:
        class: AppBundle\Admin\OrganisationAdmin
        arguments: [~, AppBundle\Entity\Organisation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Address Book', label: Organisations }

    app.admin.contact:
        class: AppBundle\Admin\ContactAdmin
        arguments: [~, AppBundle\Entity\Contact, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Address Book', label: Contacts }

